spring.application.name=the-vault
spring.config.import=optional:file:.env.properties,optional:file:backend/vault/.env.properties,optional:file:vault/.env.properties
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/the-vault}
app.aws.region=${AWS_REGION:ap-south-1}
app.aws.s3.bucket=${S3_BUCKET:}
app.aws.access-key-id=${AWS_ACCESS_KEY_ID:}
app.aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:}
app.aws.session-token=${AWS_SESSION_TOKEN:}
server.port=8080
